# Generated by Django 4.0.6 on 2022-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=32)),
                ('book1_title', models.TextField(default='', max_length=64)),
                ('book1_date', models.TextField(default='')),
                ('book1_image', models.TextField(default='')),
                ('book1_author', models.TextField(default='')),
                ('book2_title', models.TextField(default='', max_length=64)),
                ('book2_date', models.TextField(default='')),
                ('book2_image', models.TextField(default='')),
                ('book2_author', models.TextField(default='')),
                ('book3_title', models.TextField(default='', max_length=64)),
                ('book3_date', models.TextField(default='')),
                ('book3_image', models.TextField(default='')),
                ('book3_author', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='', max_length=32)),
                ('movie1_title', models.TextField(default='', max_length=64)),
                ('movie1_year', models.IntegerField(default='')),
                ('movie1_image', models.TextField(default='')),
                ('movie1_actor1', models.TextField(default='')),
                ('movie1_actor2', models.TextField(default='')),
                ('movie1_actor3', models.TextField(default='')),
                ('movie2_title', models.TextField(default='', max_length=64)),
                ('movie2_year', models.IntegerField(default='')),
                ('movie2_image', models.TextField(default='')),
                ('movie2_actor1', models.TextField(default='')),
                ('movie2_actor2', models.TextField(default='')),
                ('movie2_actor3', models.TextField(default='')),
                ('movie3_title', models.TextField(default='', max_length=64)),
                ('movie3_year', models.IntegerField(default=0)),
                ('movie3_image', models.TextField(default='')),
                ('movie3_actor1', models.TextField(default='')),
                ('movie3_actor2', models.TextField(default='')),
                ('movie3_actor3', models.TextField(default='')),
            ],
        ),
    ]
