# Generated by Django 3.2.5 on 2022-08-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artists', models.CharField(max_length=120)),
                ('acousticness', models.FloatField(max_length=120)),
                ('danceability', models.FloatField(max_length=120)),
                ('valence', models.FloatField(max_length=120)),
                ('instrumentalness', models.FloatField(max_length=120)),
                ('energy', models.FloatField(max_length=120)),
                ('speechiness', models.FloatField(max_length=120)),
                ('tempo', models.FloatField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.FloatField(max_length=120)),
                ('danceability', models.FloatField(max_length=120)),
                ('valence', models.FloatField(max_length=120)),
                ('instrumentalness', models.FloatField(max_length=120)),
                ('energy', models.FloatField(max_length=120)),
                ('speechiness', models.FloatField(max_length=120)),
                ('tempo', models.FloatField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_simi', models.CharField(max_length=10000)),
            ],
        ),
    ]
