# Generated by Django 3.2.5 on 2022-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_right',
        ),
        migrations.AddField(
            model_name='answer',
            name='weight',
            field=models.FloatField(default=0.0, max_length=120),
        ),
    ]
